name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start SSH Agent and Add Key
        run: |
          eval "$(ssh-agent -s)"  # SSH-Agent starten
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > private_key
          chmod 600 private_key
          ssh-add private_key     # Schl端ssel hinzuf端gen

      - name: Verify SSH Key
        run: ssh-add -l           # Geladene Schl端ssel pr端fen

      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no moritz@159.69.153.5 echo "Connection successful"
