name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Tools
        run: sudo apt-get install -y openssh-client

      - name: Add SSH Key
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > private_key
          chmod 600 private_key
          eval "$(ssh-agent -s)"
          ssh-add private_key

      - name: Verify SSH Key
        run: ssh-add -l

      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no moritz@159.69.153.5 echo "Connection successful"

      - name: Deploy Application
        run: |
          scp target/webserver-backend.jar moritz@159.69.153.5:/opt/backend/bin/
          ssh moritz@159.69.153.5 "sudo systemctl restart backend"
